# Generated by Django 5.1.1 on 2024-09-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uploaddp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddp',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
