# Generated by Django 5.1.1 on 2025-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_uploaddp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats', models.CharField(max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
