# Generated by Django 5.1.1 on 2025-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_recents'),
    ]

    operations = [
        migrations.AddField(
            model_name='recents',
            name='room_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recents',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
