# Generated by Django 5.1.1 on 2025-03-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_recents_room_name_recents_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recents',
            name='join_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
